//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachedMent
    {
        public System.Guid AttachedId { get; set; }
        public Nullable<System.Guid> WorkId { get; set; }
        public string AttachedUrl { get; set; }
        public string AttchedType { get; set; }
        public Nullable<System.DateTime> AttchedInserTime { get; set; }
        public string AttchedRemark { get; set; }
        public int AttchSeq { get; set; }
    
        public virtual Math_Work Math_Work { get; set; }
    }
}
