//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Math_Work()
        {
            this.AttachedMent = new HashSet<AttachedMent>();
            this.Math_Work_History = new HashSet<Math_Work_History>();
        }
    
        public System.Guid WorkId { get; set; }
        public string WorkName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Target { get; set; }
        public string ShoolName { get; set; }
        public int WorkSeq { get; set; }
        public string PointWhoNumber { get; set; }
        public string PointWho { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<System.DateTime> BegTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string JiaotongFangshi { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CreateDeptId { get; set; }
        public string UserAccount { get; set; }
        public string UserName { get; set; }
        public string UserTelNumber { get; set; }
        public string UserDeptName { get; set; }
        public Nullable<int> InfactFee { get; set; }
        public Nullable<System.DateTime> ShenPiRiQi { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachedMent> AttachedMent { get; set; }
        public virtual Math_Deptinfo Math_Deptinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Math_Work_History> Math_Work_History { get; set; }
    }
}
