//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_SYJD
    {
        public System.Guid SYJDId { get; set; }
        public string GrandSchool { get; set; }
        public string Who { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string DataFrom { get; set; }
    }
}
