//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AnalySISS
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JYT_Id { get; set; }
        public string JYT_StudentName { get; set; }
        public string JYT_IdCard { get; set; }
        public string JYT_StudentSex { get; set; }
        public string JYT_GrandSchool { get; set; }
        public Nullable<System.DateTime> JYT_InsertTime { get; set; }
        public Nullable<System.DateTime> JYT_LastUpdateTime { get; set; }
        public string JYT_DataFrom { get; set; }
        public string XSC_IdCard { get; set; }
        public string ZS_IdCard { get; set; }
        public string SYJD_GrandSchool { get; set; }
        public string SYJD_Who { get; set; }
        public string CWC_IdCard { get; set; }
        public string ZS_Who { get; set; }
        public string XSC_StudentName { get; set; }
        public string tuijianren { get; set; }
        public int tuijianrentype { get; set; }
        public int FeeItems { get; set; }
        public string ZSLB { get; set; }
        public string Resault_Who { get; set; }
        public int name_Check { get; set; }
        public string name_Check_Content { get; set; }
        public string Area { get; set; }
    }
}
