//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ZhanZhangStaticBase
    {
        public System.Guid XSCId { get; set; }
        public string IdCard { get; set; }
        public string StudentName { get; set; }
        public string StudentNumber { get; set; }
        public string DictValue { get; set; }
        public string DictRemark { get; set; }
        public string zhanzhangdaqu { get; set; }
        public string zhanzhang { get; set; }
        public string zhanzhangquyu { get; set; }
        public string GrandSchool { get; set; }
    }
}
