//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User_Role
    {
        public System.Guid RoleId { get; set; }
        public int RoleOrderId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RoleStatus { get; set; }
        public Nullable<System.DateTime> RoleInsertTime { get; set; }
        public Nullable<System.DateTime> RoleUpdateTime { get; set; }
        public string RoleRemark { get; set; }
        public System.Guid UserId { get; set; }
        public int UserOrderId { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string UserAddress { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserTel { get; set; }
        public string UserPwd { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<System.DateTime> UserInsertTime { get; set; }
        public Nullable<System.DateTime> UserUpdateTime { get; set; }
    }
}
