//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User_Menu
    {
        public System.Guid UserId { get; set; }
        public System.Guid MenuId { get; set; }
        public int MenuOrderId { get; set; }
        public string MenuTitle { get; set; }
        public string MenuRemark { get; set; }
        public string MenuURL { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<System.DateTime> MenuInsertTime { get; set; }
        public Nullable<System.DateTime> MenuUpdateTime { get; set; }
        public int UserOrderId { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string UserPhone { get; set; }
        public string UserTel { get; set; }
        public string UserPwd { get; set; }
        public Nullable<System.DateTime> UserInsertTime { get; set; }
        public Nullable<System.DateTime> UserUpdateTime { get; set; }
        public Nullable<System.Guid> User_Dept_Id { get; set; }
        public string User_Sex { get; set; }
        public Nullable<int> User_Area { get; set; }
        public Nullable<int> MenuOrderBy { get; set; }
    }
}
