//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZZ_Static
    {
        public System.Guid Id { get; set; }
        public string StudentName { get; set; }
        public string StudentIdCard { get; set; }
        public string StudentType { get; set; }
        public string ZhanZhangDaQuResource { get; set; }
        public string ZhanZhangDaQu { get; set; }
        public string ZhanZhang { get; set; }
        public string StudentSchool { get; set; }
    }
}
