//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseInfo
    {
        public Nullable<double> 序号 { get; set; }
        public string 专业 { get; set; }
        public string 专业ID { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 身份证号 { get; set; }
        public string 学校 { get; set; }
        public string 推荐人 { get; set; }
        public string 推荐人ID { get; set; }
        public string 推荐人部门 { get; set; }
        public string 推荐人部门ID { get; set; }
        public string 备注 { get; set; }
    }
}
