//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowserInfo
    {
        public System.Guid BrowserId { get; set; }
        public int BrowserOrderId { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public string UserName { get; set; }
        public string BrowserType { get; set; }
        public string Platform { get; set; }
        public string Frames { get; set; }
        public string Tables { get; set; }
        public string Cookies { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
