//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongsiInfo
    {
        public System.Guid GongsiID { get; set; }
        public int GongsiIndex { get; set; }
        public string GongsiName { get; set; }
        public string GongsiContent { get; set; }
        public string GongsiSearchkey { get; set; }
        public string GongsiSearchDes { get; set; }
        public string GongsiFooter { get; set; }
        public string GongsiCultrue { get; set; }
        public string GongsiShortName { get; set; }
        public string GongsiLogo { get; set; }
    }
}
