//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_Dict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Math_Dict()
        {
            this.Math_Student = new HashSet<Math_Student>();
        }
    
        public System.Guid DictId { get; set; }
        public int DictOrderId { get; set; }
        public string DictValue { get; set; }
        public Nullable<System.Guid> DictTypeId { get; set; }
        public string DictRemark { get; set; }
    
        public virtual Math_DictType Math_DictType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Math_Student> Math_Student { get; set; }
    }
}
