//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_RoleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Math_RoleInfo()
        {
            this.Math_Role_Menu_Selcet = new HashSet<Math_Role_Menu_Selcet>();
            this.Math_User_Role_Select = new HashSet<Math_User_Role_Select>();
        }
    
        public System.Guid RoleId { get; set; }
        public int RoleOrderId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RoleStatus { get; set; }
        public Nullable<System.DateTime> RoleInsertTime { get; set; }
        public Nullable<System.DateTime> RoleUpdateTime { get; set; }
        public string RoleRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Math_Role_Menu_Selcet> Math_Role_Menu_Selcet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Math_User_Role_Select> Math_User_Role_Select { get; set; }
    }
}
