//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_Student
    {
        public System.Guid StudentId { get; set; }
        public int StudentOrderId { get; set; }
        public string StudentName { get; set; }
        public string StudentIDCard { get; set; }
        public string StudentPhone { get; set; }
        public string StudentType { get; set; }
        public string StudentSchool { get; set; }
        public string StudentAddress { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string UserPhone { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserDeptId { get; set; }
        public string UserDeptName { get; set; }
        public Nullable<System.Guid> StudentZhuanYeId { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
        public string Sex { get; set; }
        public string Area { get; set; }
        public string DingZhengName { get; set; }
        public string DingZhengNumber { get; set; }
        public Nullable<System.DateTime> DingZhengUpdateTime { get; set; }
    
        public virtual Math_Dict Math_Dict { get; set; }
        public virtual Math_UserInfo Math_UserInfo { get; set; }
    }
}
