//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Math_Work_History
    {
        public System.Guid WorkHisId { get; set; }
        public int WorkHisSeq { get; set; }
        public Nullable<System.Guid> WorkId { get; set; }
        public string ShenPiRen { get; set; }
        public string ShenPiRenTel { get; set; }
        public string ShenPiJianYi { get; set; }
        public string ShenPiJianRemark { get; set; }
        public Nullable<System.DateTime> ShenPiDateTime { get; set; }
    
        public virtual Math_Work Math_Work { get; set; }
    }
}
